title: "Forms"
description: |
  Forms and inputs should be used to collect data from the viewer or to make a choice.
background: "--color-primary-light"

patterns:
    checkbox:
      title: "Checkbox"
      description: |
        Checkboxes should be used when the user has to select more then one option.
      fields:
        - name: text
          type: string
          example: "Option"
      width: "16em"
    date-picker:
      title: "Date Picker"
      description: |
        The date picker should be used when the user has to select a date.
      width: "16em"
    drop-down:
      title: "Drop Down"
      description: |
        Drop downs should be used when the user has to select one option out of specific choices given to them.
      fields:
        - name: text
          type: string
          example: "Option"
      width: "16em"
    email-input:
      title: "Email Input"
      description: |
        Email inputs are only to be used when the answer is a valid email address.
      width: "16em"
    labels:
      title: "Labels"
      description: |
        Labels are to go before all input field to give the user some direction of how to proceed.
      width: "16em"
    text-area:
      title: "Text Area"
      description: |
        Text areas should be used when the answer should be long and detailed. Any input field expecting text that is more then one sentence should use a text area.
      width: "16em"
    text-input:
      title: "Text Input"
      description: |
        Text inputs are to be used when the user is expected to give a short answer with text.
      width: "16em"
    legend:
      title: "Legend"
      description: |
        Legends are used as labels for fieldset.
      width: "16em"
