title: "Cards"
description: |
  Cards should be used when there are multiple image and type groups.

patterns:
    category:
      title: "Category Card"
      description: |
        Category is to be used on the homepage to lead the viewer to either the sweet or the savory page. Both shall include a heading, some descriptive text and a button.
      fields:
        - name: heading
          type: string
          example: "Sweet"
        - name: text
          type: string
          example: "Sweet, sugary treats to sooth your sweet-tooth."
        - name: image
          type: string
          example: "/images/pink-pastries.jpg"
        - name: button_text
          type: string
          example: "Seem more"
          required: false
        - name: button_url
          type: url
          example: "/products/"
          required: false
    product:
      title: "Product Card"
      description: |
        Product cards are used to lead users to the product details page of the product listed.
      fields:
        - name: heading
          type: string
          example: "Raspberry Macaron"
        - name: image
          type: string
          example: "/images/product/card-raspberry-macaron.png"
